#!/usr/bin/env bash

# Check if $1 (first argument) is set, else prompt the user to input name
if [[ -n $1 ]]; then
  name=$1
else
  read -p 'Enter your name: ' name
fi
echo "Hello, $name"
echo "Hello, World!"
