#!/usr/bin/env bash

greet() {
  local name=$1 # By default the variable is global, should add local keyword to make the variable local
  echo "Hello, $name"
}

for name in "$@"; do
  greet "$name"
done
