#!/usr/bin/env bash

a=2
b=2

if [[ $a == $b ]]; then
  echo 'a and b are the same'
fi

c=2
d=3

if [[ $c != $d ]]; then
  echo 'c and d are not same'
fi

if [[ -f 007_functions ]]; then
  echo '007_functions exists and is a file'
fi

if ! [[ -f 009_test ]]; then
  echo '009_test either does not exist or is not a file'
fi

while [[ -f 009_test ]]; do
  echo '009_test exists and is a file'
  sleep 1
done

# until is the opposite of while
# until [[ -f 009_test ]]; do
#   echo '009_test either does not exist or is not a file'
#   sleep 1
# done

if ls; then
  echo "ls worked"
fi
